### ISSUE TITLE
Fail to use item

### ISSUE THREAD

**Issue by Bassedetmig97** [Crazy133/crazy-kidnapping#1]
script:qb-zipties] SCRIPT ERROR: @qb-zipties/Server/main.lua:19: attempt to call a nil value (field 'HasItem')
[   script:qb-zipties] > UseItem (@qb-core/server/functions.lua:221)
[   script:qb-zipties] > handler (@qb-core/server/events.lua:182)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by Crazy133** [comment]
- Are you running the latest QBCore update?
- Are you using a specific item in the Config?
